model builders added
InteIIigeNET/Alice.NET pull request #4
Opened 2018-08-05 20:18 UTC by DedSec256

2018-08-06 06:34 UTC, DedSec256 commented on Alice.NET/Images/ImagesApi.cs
> +	public class ImagesApi
Тут бы я, на самом деле, выделил интерфейс.

2018-08-06 10:29 UTC, DedSec256 commented on Alice.NET/Images/ImagesApi.cs
> +			Client.DefaultRequestHeaders.Add("Host", "https://dialogs.yandex.net");
Тут, увы, потенциальная бага, ибо, если создать несколько экземпляров класса - у их статического HttpClient будет попытка повторного добавления тех же header-ов. Хз пока что, насколько критично

2018-08-06 20:31 UTC, mshamrai requested changes

2018-08-06 20:31 UTC, MaxVortman commented on Alice.NET/Models/Cards/Card.cs
> +			Type = type;
Вообще это не нравится. Поле можно инитить и так:
```` c#
public CardType Type { get; set; } = CardType.BigImage;
````
Ради одного поля создавать базовый класс? Чет не очень.
К тому же BigImageCard и CardItem дублируют код друг друга (и как следствие их билдеры тоже). Уж лучше сделать базовый класс под их поля, дабы избежать дублирования.

2018-08-06 20:31 UTC, MaxVortman commented on Alice.NET/Models/Cards/Card.cs
> +	public enum CardType
Хочу отдельную директорию Enums, где такое лежать будет. 
А то не ясно, где искать в случае чего.

2018-08-06 20:31 UTC, MaxVortman commented on Alice.NET/Models/Builders/Cards/ItemsListCardBuilder.cs
> +			return this;
Не нравится такой способ задания хедера и футера. 
Считаю, что лучше бы так:
``` c#
public ItemsListCardBuilder WithFooter(Func<FooterBuilder, Footer> buildFooterFunc)
{
    Card.Footer = buildFooterFunc(new FooterBuilder());
    return this;
}
```
Тогда пользователь будет пользоваться более привлекательным вариантом:
``` c#
cardBuilder.WithFooter(fb =>
   fb....
    .Build();
);
```

2018-08-06 20:31 UTC, MaxVortman commented on Alice.NET/Models/Builders/Responses/ResponseBuilder.cs
> +			return this;
Тут тоже, что и с футером. 
Мне не хотелось бы отдельно использовать много билдеров. 
Кстати, их конструкторы можно скрыть как internal.

2018-08-06 20:47 UTC, DedSec256 commented on Alice.NET/Models/Builders/Cards/ItemsListCardBuilder.cs
> +			return this;
@MaxVortman тоже думал об этом. Тогда нужно будет то же самое провернуть везде и для Button. И я бы не убирал WithFooter(Footer footer), а лишь добавил бы твою перегрузку, ибо хз, как юзер собирается добавлять их.

2018-08-06 20:50 UTC, DedSec256 commented on Alice.NET/Images/ImagesApi.cs
> +		private readonly IJsonSerializer _jsonSerializer = new JsonSerializer.JsonSerializer(); //чёт не нравится такая интеграция зависимостей
@MaxVortman. При инициализации ioc нужно будет сконфигурировать его, чтобы он просматривал только сборку Alice.NET, в любом случае, он лишь создаст накладные расходы, а нужен не в таком уж и большом количестве мест. Нужно ли нам тянуть за собой груз в виде ioc в таком небольшом проекте, к тому же, это будет неочевидно для пользователей, что там где-то конейнер что-то инициализирует? Нужно подумать.

2018-08-06 20:53 UTC, MaxVortman commented on Alice.NET/Images/ImagesApi.cs
> +		private readonly IJsonSerializer _jsonSerializer = new JsonSerializer.JsonSerializer(); //чёт не нравится такая интеграция зависимостей
@DedSec256 В рамках нашей сборки просматривать ничего не надо. Можем пихать нативно.

2018-08-06 21:09 UTC, DedSec256 commented on Alice.NET/Models/Cards/Card.cs
> +			Type = type;
@MaxVortman, мне тоже не очень нравится, я подумаю, что можно сделать ещё покрасивее.

2018-08-06 21:11 UTC, DedSec256 commented on Alice.NET/Images/ImagesApi.cs
> +		private readonly IJsonSerializer _jsonSerializer = new JsonSerializer.JsonSerializer(); //чёт не нравится такая интеграция зависимостей
@MaxVortman, я уже и отвык что-то вручную пихать :D
Тогда пойдёт.

2018-08-18 23:29 UTC, DedSec256 commented on Alice.NET/Models/Cards/ItemsListCard.cs
> +					item.Type = null;
Зато теперь у нас есть инвариантный конракт)!0!))

2018-08-18 23:31 UTC, DedSec256 commented on Alice.NET/Models/Builders/Cards/BigImageCardBuilder.cs
> +	public interface IBigImageCardBuilder : IImageCardBuilder
чтобы не создавать его интерфейс и реализацию, можно в ```IImageCardBuilder``` добавить ```CreateBigImageCard()```. Но тогда мы не сможем вообще различить билдер для обычного CardItem и BigImageCard

2018-08-19 16:14 UTC, DedSec256 commented on Alice.NET/Models/Cards/ItemsListCard.cs
> +					item.Type = null;
Но осталась проблема ссылочного типа - один из объектов массива могут поменять случайно позже. Хуёво, чё.

2021-02-14 12:41 UTC, closed without merging